from app.schemas.source import Source, SourceCategory, SourceStatus

SOURCES: list[Source] = [
    Source(
        id="mock_demand",
        name="Mock Electricity Demand",
        description="Synthetic hourly electricity demand data for New Hampshire. Used for development and testing of the full fetch/clean/export pipeline.",
        category=SourceCategory.electricity,
        status=SourceStatus.mock,
        update_frequency="On demand",
        data_format="CSV",
        notes="Generates realistic diurnal and weekly demand curves. Not real data.",
    ),
    Source(
        id="eia_isone_load",
        name="EIA ISO-NE Hourly Load",
        description="Hourly electricity load data for ISO New England from the U.S. Energy Information Administration open data API.",
        category=SourceCategory.electricity,
        status=SourceStatus.planned,
        url="https://api.eia.gov/v2/electricity/rto/region-data/data/",
        update_frequency="Hourly",
        data_format="JSON",
        notes="Requires EIA_API_KEY environment variable. Free registration at eia.gov/opendata.",
    ),
    Source(
        id="noaa_weather",
        name="NOAA Weather",
        description="Historical and recent weather observations from NOAA stations in New Hampshire (Manchester, Concord, Portsmouth).",
        category=SourceCategory.weather,
        status=SourceStatus.planned,
        url="https://www.ncdc.noaa.gov/cdo-web/api/v2/data",
        update_frequency="Daily",
        data_format="JSON",
        notes="Requires NOAA_TOKEN environment variable. Free at ncdc.noaa.gov/cdo-web/token.",
    ),
    Source(
        id="isone_csv",
        name="ISO-NE CSV Downloads",
        description="Public ISO New England CSV download support. Phase 10 starts with hourly real-time system demand via direct CSV export.",
        category=SourceCategory.electricity,
        status=SourceStatus.active,
        url="https://www.iso-ne.com/isoexpress/web/reports/load-and-demand/-/tree/dmnd-rt-hourly-sys",
        update_frequency="Daily",
        data_format="CSV",
        notes="No API key required. Current implementation fetches the public Hourly Real-Time System Demand CSV.",
    ),
    Source(
        id="afdc_ev",
        name="AFDC EV Charging Stations",
        description="Electric vehicle charging station locations in New Hampshire from the Alternative Fuels Data Center (NREL).",
        category=SourceCategory.ev,
        status=SourceStatus.active,
        url="https://developer.nrel.gov/api/alt-fuel-stations/v1.json",
        update_frequency="Weekly",
        data_format="JSON",
        notes="Uses DEMO_KEY by default (30 req/day). Set NREL_API_KEY in .env for higher limits. Free at developer.nrel.gov.",
    ),
    Source(
        id="openei_rates",
        name="OpenEI Utility Rates",
        description="Residential utility rate context from OpenEI's U.S. Utility Rate Database, centered on New Hampshire service territory.",
        category=SourceCategory.electricity,
        status=SourceStatus.active,
        url="https://api.openei.org/utility_rates",
        update_frequency="As updated",
        data_format="JSON",
        notes="Current implementation fetches approved default residential rates near Manchester, NH. Tries public access first; OPENEI_API_KEY can be set if the service requires a key.",
    ),
    Source(
        id="epa_egrid",
        name="EPA eGRID",
        description="EPA eGRID subregion emissions context from the public summary data release, including CO2e, NOx, and SO2 output emission rates.",
        category=SourceCategory.environmental,
        status=SourceStatus.active,
        url="https://www.epa.gov/egrid/summary-data",
        update_frequency="Annual",
        data_format="HTML/CSV",
        notes="Current implementation ingests the public subregion output emissions summary table from EPA's latest eGRID release.",
    ),
    Source(
        id="fema_flood",
        name="FEMA Flood Maps",
        description="National Flood Insurance Program (NFIP) flood zone boundaries for New Hampshire municipalities.",
        category=SourceCategory.resilience,
        status=SourceStatus.planned,
        url="https://msc.fema.gov/portal/home",
        update_frequency="As updated",
        data_format="GeoJSON/Shapefile",
    ),
    Source(
        id="epa_ejscreen",
        name="EPA EJScreen",
        description="Environmental justice screening and mapping data for New Hampshire census tracts — pollution burden and demographic indicators.",
        category=SourceCategory.environmental,
        status=SourceStatus.planned,
        url="https://ejscreen.epa.gov/mapper/",
        update_frequency="Annual",
        data_format="CSV",
    ),
    Source(
        id="cdc_svi",
        name="CDC Social Vulnerability Index",
        description="CDC/ATSDR Social Vulnerability Index for New Hampshire. Supports equity-aware utility planning and resilience analysis.",
        category=SourceCategory.resilience,
        status=SourceStatus.planned,
        url="https://www.atsdr.cdc.gov/placeandhealth/svi/data_documentation_download.html",
        update_frequency="Every 2 years",
        data_format="CSV",
    ),
    Source(
        id="manchester_gis",
        name="Manchester GIS",
        description="Geographic information system data for the City of Manchester, NH — infrastructure, parcels, zoning, and utilities.",
        category=SourceCategory.gis,
        status=SourceStatus.planned,
        url="https://www.manchesternh.gov/Departments/Information-Technology/GIS",
        update_frequency="As updated",
        data_format="Shapefile/GeoJSON",
    ),
    Source(
        id="nh_geodata",
        name="NH Geodata (GRANIT)",
        description="UNH statewide New Hampshire GIS repository — roads, utilities, municipal boundaries, and environmental layers.",
        category=SourceCategory.gis,
        status=SourceStatus.planned,
        url="https://www.granit.unh.edu/",
        update_frequency="As updated",
        data_format="Shapefile/GeoJSON",
    ),
    Source(
        id="nhsaves",
        name="NHSaves",
        description="Public program information for New Hampshire energy efficiency programs. Eversource-adjacent public data.",
        category=SourceCategory.regulatory,
        status=SourceStatus.planned,
        url="https://www.nhsaves.com/",
        update_frequency="As published",
        data_format="HTML/PDF",
        notes="Not official Eversource software. Public data relevant to New Hampshire utility analysis.",
    ),
    Source(
        id="nh_puc",
        name="NH Public Utilities Commission",
        description="Regulatory filings, rate cases, dockets, and orders from the NH PUC. Public record.",
        category=SourceCategory.regulatory,
        status=SourceStatus.planned,
        url="https://www.puc.nh.gov/",
        update_frequency="As filed",
        data_format="PDF/HTML",
    ),
    Source(
        id="eversource_sustainability",
        name="Eversource Sustainability Reports",
        description="Publicly available sustainability, ESG, and grid modernization reports from Eversource Energy.",
        category=SourceCategory.regulatory,
        status=SourceStatus.planned,
        url="https://www.eversource.com/content/general/about/sustainability",
        update_frequency="Annual",
        data_format="PDF",
        notes="Public data relevant to New Hampshire utility analysis. Not official Eversource software.",
    ),
]

SOURCES_BY_ID: dict[str, Source] = {s.id: s for s in SOURCES}
