from app.schemas.source import Source, SourceCategory, SourceStatus

SOURCES: list[Source] = [
    # ── Active: no key required ───────────────────────────────────────────────
    Source(
        id="isone_csv",
        name="ISO-NE CSV Downloads",
        description="Public ISO New England CSV download — hourly real-time system demand via direct public export.",
        category=SourceCategory.electricity,
        status=SourceStatus.active,
        url="https://www.iso-ne.com/isoexpress/web/reports/load-and-demand/-/tree/dmnd-rt-hourly-sys",
        update_frequency="Daily",
        data_format="CSV",
        notes="No API key required. Fetches the public Hourly Real-Time System Demand CSV.",
        requires_api_key=False,
        auth_type="none",
        access_type="public_csv",
        data_geography="iso_ne",
        phase_added=10,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="afdc_ev",
        name="AFDC EV Charging Stations",
        description="Electric vehicle charging station locations in New Hampshire from the Alternative Fuels Data Center (NREL).",
        category=SourceCategory.ev,
        status=SourceStatus.active,
        url="https://developer.nrel.gov/api/alt-fuel-stations/v1.json",
        update_frequency="Weekly",
        data_format="JSON",
        notes="Uses DEMO_KEY by default (30 req/day). Set NREL_API_KEY in .env for higher limits. Free at developer.nrel.gov.",
        requires_api_key=False,
        api_key_env_var="NREL_API_KEY",
        auth_type="api_key",
        access_type="public_api_no_key",
        data_geography="nh",
        phase_added=6,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="openei_rates",
        name="OpenEI Utility Rates",
        description="Residential utility rate context from OpenEI's U.S. Utility Rate Database, centered on New Hampshire service territory.",
        category=SourceCategory.electricity,
        status=SourceStatus.active,
        url="https://api.openei.org/utility_rates",
        update_frequency="As updated",
        data_format="JSON",
        notes="Tries public access first. Set OPENEI_API_KEY in .env if the public tier is unavailable.",
        requires_api_key=False,
        api_key_env_var="OPENEI_API_KEY",
        auth_type="api_key",
        access_type="public_api_no_key",
        data_geography="nh",
        phase_added=11,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="epa_egrid",
        name="EPA eGRID",
        description="EPA eGRID subregion output emission rates — CO2e, NOx, SO2 — from the latest public summary data release.",
        category=SourceCategory.environmental,
        status=SourceStatus.active,
        url="https://www.epa.gov/egrid/summary-data",
        update_frequency="Annual",
        data_format="HTML/CSV",
        notes="No API key required. Parses the public subregion emissions summary table from EPA's eGRID website.",
        requires_api_key=False,
        auth_type="none",
        access_type="public_web_scrape",
        data_geography="national",
        phase_added=11,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="fema_flood",
        name="FEMA Flood Maps",
        description="FEMA National Flood Hazard Layer (NFHL) flood zone boundaries for New Hampshire — AE, X, VE, and other flood designations by county.",
        category=SourceCategory.resilience,
        status=SourceStatus.active,
        url="https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer",
        update_frequency="As updated",
        data_format="JSON",
        notes="No API key required. Returns tabular flood zone attributes from the FEMA NFHL ArcGIS REST service, filtered to the NH bounding box. Results may be capped at 2,000 records.",
        requires_api_key=False,
        auth_type="none",
        access_type="arcgis_rest",
        data_geography="nh",
        phase_added=12,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="cdc_svi",
        name="CDC Social Vulnerability Index",
        description="CDC/ATSDR Social Vulnerability Index (SVI 2022) for New Hampshire census tracts. Four theme percentiles support equity-aware utility and resilience planning.",
        category=SourceCategory.resilience,
        status=SourceStatus.active,
        url="https://svi.cdc.gov/Documents/Data/2022/csv/states/NewHampshire.csv",
        update_frequency="Every 2 years",
        data_format="CSV",
        notes="No API key required. Downloads the 2022 CDC/ATSDR SVI state CSV for New Hampshire. Values of -999 indicate census tracts with insufficient data.",
        requires_api_key=False,
        auth_type="none",
        access_type="public_csv",
        data_geography="nh",
        phase_added=12,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="nh_geodata",
        name="NH Geodata (GRANIT)",
        description="NH municipal geography — all NH towns and cities with county, FIPS codes, and 2020 Census population. Provides the geographic foundation for NH utility and resilience analysis.",
        category=SourceCategory.gis,
        status=SourceStatus.active,
        url="https://www.granit.unh.edu/",
        update_frequency="Decennial",
        data_format="JSON",
        notes="No API key required. Fetches NH county subdivision data from the US Census 2020 Decennial API. GRANIT (granit.unh.edu) provides additional statewide GIS layers.",
        requires_api_key=False,
        auth_type="none",
        access_type="public_api_no_key",
        data_geography="nh",
        phase_added=12,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),

    Source(
        id="eia_ami",
        name="EIA AMI Smart Meter Deployment",
        description="Advanced metering infrastructure (AMI/smart meter) deployment by NH utility — annual counts of total customers, AMI customers, and penetration rate from EIA Form 861.",
        category=SourceCategory.electricity,
        status=SourceStatus.active,
        url="https://www.eia.gov/electricity/data/eia861/",
        update_frequency="Annual",
        data_format="Excel (ZIP)",
        notes=(
            "No API key required. Downloads the EIA Form 861 annual ZIP and extracts "
            "the Advanced_Meters Excel file. Tries survey years 2024 → 2023 → 2022 in order. "
            "Requires openpyxl. Column names are verified via keyword matching and may need "
            "adjustment if EIA changes the spreadsheet layout in future releases."
        ),
        requires_api_key=False,
        auth_type="none",
        access_type="public_zip_excel",
        data_geography="nh",
        phase_added=15,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="nrel_pvwatts",
        name="NREL PVWatts Solar Estimates",
        description="Monthly solar PV output estimates for key NH locations (Manchester, Concord, Portsmouth, Keene) — 4 kW residential reference system. From NREL PVWatts v8.",
        category=SourceCategory.solar,
        status=SourceStatus.active,
        url="https://developer.nrel.gov/api/pvwatts/v8.json",
        update_frequency="On demand",
        data_format="JSON",
        notes="Uses DEMO_KEY by default (limited rate). Set NREL_API_KEY in .env for higher limits — same key as AFDC EV stations. Free at developer.nrel.gov.",
        requires_api_key=False,
        api_key_env_var="NREL_API_KEY",
        auth_type="api_key",
        access_type="public_api_no_key",
        data_geography="nh",
        phase_added=14,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="isone_fuel_mix",
        name="ISO-NE Generation Fuel Mix",
        description="ISO New England hourly electricity generation by fuel type — natural gas, nuclear, hydro, solar, wind, and more. Public CSV export.",
        category=SourceCategory.electricity,
        status=SourceStatus.active,
        url="https://www.iso-ne.com/isoexpress/web/reports/operations/-/tree/gen-fuel-mix",
        update_frequency="Hourly",
        data_format="CSV",
        notes="No API key required. Fetches 7 days of generation-by-fuel data from the ISO-NE public transform/csv endpoint.",
        requires_api_key=False,
        auth_type="none",
        access_type="public_csv",
        data_geography="iso_ne",
        phase_added=13,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="isone_load_forecast",
        name="ISO-NE Hourly Load Forecast",
        description="ISO New England hourly load forecast — projected system-wide electricity demand for the next 7 days. Public CSV export.",
        category=SourceCategory.electricity,
        status=SourceStatus.active,
        url="https://www.iso-ne.com/isoexpress/web/reports/load-and-demand/-/tree/hourly-load-forecast",
        update_frequency="Hourly",
        data_format="CSV",
        notes="No API key required. Fetches 7 days of hourly load forecast data from the ISO-NE public transform/csv endpoint.",
        requires_api_key=False,
        auth_type="none",
        access_type="public_csv",
        data_geography="iso_ne",
        phase_added=13,
        last_verified="2026-04-27",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),

    # ── Requires API key ─────────────────────────────────────────────────────
    Source(
        id="eia_ng_prices",
        name="EIA Natural Gas Retail Prices",
        description=(
            "Monthly retail natural gas prices for New Hampshire by sector "
            "(residential, commercial, industrial) in $/MCF — from the EIA v2 API. "
            "Natural gas is the dominant ISO-NE generation fuel and the primary driver "
            "of NH electricity price volatility."
        ),
        category=SourceCategory.gas,
        status=SourceStatus.requires_key,
        url="https://api.eia.gov/v2/natural-gas/pri/sum/data/",
        update_frequency="Monthly",
        data_format="JSON",
        notes=(
            "Requires EIA_API_KEY in .env — same key as EIA Retail Electricity Prices "
            "and EIA ISO-NE Hourly Load. Free registration at eia.gov/opendata. "
            "Returns 5 years of monthly NH retail NG prices in $/MCF by sector."
        ),
        requires_api_key=True,
        api_key_env_var="EIA_API_KEY",
        auth_type="api_key",
        access_type="public_api_key_required",
        data_geography="nh",
        phase_added=17,
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="eia_retail_prices",
        name="EIA Retail Electricity Prices",
        description="Average retail electricity prices for New Hampshire by sector (residential, commercial, industrial) — monthly data from the EIA open data API.",
        category=SourceCategory.electricity,
        status=SourceStatus.requires_key,
        url="https://api.eia.gov/v2/electricity/retail-sales/data/",
        update_frequency="Monthly",
        data_format="JSON",
        notes="Requires EIA_API_KEY in .env. Free registration at eia.gov/opendata. Returns 4 years of monthly NH average retail prices in cents per kWh by sector.",
        requires_api_key=True,
        api_key_env_var="EIA_API_KEY",
        auth_type="api_key",
        access_type="public_api_key_required",
        data_geography="nh",
        phase_added=14,
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="eia_isone_load",
        name="EIA ISO-NE Hourly Load",
        description="Hourly electricity load data for ISO New England from the U.S. Energy Information Administration open data API.",
        category=SourceCategory.electricity,
        status=SourceStatus.requires_key,
        url="https://api.eia.gov/v2/electricity/rto/region-data/data/",
        update_frequency="Hourly",
        data_format="JSON",
        notes="Requires EIA_API_KEY in .env. Free registration at eia.gov/opendata.",
        requires_api_key=True,
        api_key_env_var="EIA_API_KEY",
        auth_type="api_key",
        access_type="public_api_key_required",
        data_geography="iso_ne",
        phase_added=3,
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="noaa_weather",
        name="NOAA Weather",
        description="Historical and recent weather observations from NOAA stations in New Hampshire (Manchester, Concord, Portsmouth).",
        category=SourceCategory.weather,
        status=SourceStatus.requires_key,
        url="https://www.ncdc.noaa.gov/cdo-web/api/v2/data",
        update_frequency="Daily",
        data_format="JSON",
        notes="Requires NOAA_TOKEN in .env. Free at ncdc.noaa.gov/cdo-web/token.",
        requires_api_key=True,
        api_key_env_var="NOAA_TOKEN",
        auth_type="token",
        access_type="public_api_key_required",
        data_geography="nh",
        phase_added=4,
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),

    # ── Research / under evaluation ───────────────────────────────────────────
    Source(
        id="isone_lmp",
        name="ISO-NE Wholesale LMP Prices",
        description="ISO New England real-time hourly locational marginal prices (LMP) for all load zones and hubs — total, energy, congestion, and loss components. Public transform/csv export.",
        category=SourceCategory.electricity,
        status=SourceStatus.active,
        url="https://www.iso-ne.com/isoexpress/web/reports/pricing/-/tree/zone-info",
        update_frequency="Hourly",
        data_format="CSV",
        notes=(
            "No API key required. Fetches 7 days of hourly LMP from the ISO-NE public "
            "transform/csv endpoint. Returns all zones in long format; NH zone is identified "
            "as '.Z.NEWHAMPSHIRE'. Endpoint URL and column names need live verification — "
            "see connector TODO."
        ),
        requires_api_key=False,
        auth_type="none",
        access_type="public_csv",
        data_geography="iso_ne",
        phase_added=15,
        last_verified="2026-04-28",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="manchester_gis",
        name="Manchester GIS",
        description="Geographic information system data for the City of Manchester, NH — infrastructure, parcels, zoning, and utilities.",
        category=SourceCategory.gis,
        status=SourceStatus.research,
        url="https://www.manchesternh.gov/Departments/Information-Technology/GIS",
        update_frequency="As updated",
        data_format="Shapefile/GeoJSON",
        notes="No confirmed stable programmatic API. City ArcGIS portal access is being evaluated.",
        requires_api_key=False,
        access_type="arcgis_rest",
        data_geography="nh",
        phase_added=1,
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=False,
    ),

    # ── Not implemented (catalog placeholders) ────────────────────────────────
    Source(
        id="epa_ejscreen",
        name="EPA EJScreen",
        description=(
            "EPA EJScreen 2023 block-group environmental justice indicators for New Hampshire — "
            "pollution burden percentiles (PM2.5, diesel, cancer risk, traffic) and demographic "
            "indicators (low income, people of color, linguistic isolation). Complements CDC SVI "
            "for equity-aware utility planning."
        ),
        category=SourceCategory.environmental,
        status=SourceStatus.active,
        url="https://ejscreen.epa.gov/mapper/",
        update_frequency="Annual",
        data_format="JSON",
        notes=(
            "No API key required. Queries the EPA EJScreen 2023 ArcGIS Feature Service "
            "(ArcGIS Online) for all NH block groups, filtered by bounding box and state code. "
            "Returns ~1,270 block groups with 20 EJ indicator percentiles. "
            "ArcGIS service URL subject to change on annual data releases — see connector TODO."
        ),
        requires_api_key=False,
        auth_type="none",
        access_type="arcgis_rest",
        data_geography="nh",
        phase_added=16,
        last_verified="2026-04-28",
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=True,
    ),
    Source(
        id="nhsaves",
        name="NHSaves",
        description="Public program information for New Hampshire energy efficiency programs. Eversource-adjacent public data.",
        category=SourceCategory.regulatory,
        status=SourceStatus.not_implemented,
        url="https://www.nhsaves.com/",
        update_frequency="As published",
        data_format="HTML/PDF",
        notes="Not official Eversource software. Public data relevant to New Hampshire utility analysis. No structured API; connector would require HTML or PDF parsing.",
        requires_api_key=False,
        access_type="public_web_scrape",
        data_geography="nh",
        phase_added=1,
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=False,
    ),
    Source(
        id="nh_puc",
        name="NH Public Utilities Commission",
        description="Regulatory filings, rate cases, dockets, and orders from the NH PUC. Public record.",
        category=SourceCategory.regulatory,
        status=SourceStatus.not_implemented,
        url="https://www.puc.nh.gov/",
        update_frequency="As filed",
        data_format="PDF/HTML",
        notes="No structured API. Documents are PDF filings. Connector would require document scraping.",
        requires_api_key=False,
        access_type="manual_download",
        data_geography="nh",
        phase_added=1,
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=False,
    ),
    Source(
        id="eversource_sustainability",
        name="Eversource Sustainability Reports",
        description="Publicly available sustainability, ESG, and grid modernization reports from Eversource Energy.",
        category=SourceCategory.regulatory,
        status=SourceStatus.not_implemented,
        url="https://www.eversource.com/content/general/about/sustainability",
        update_frequency="Annual",
        data_format="PDF",
        notes="Public data relevant to New Hampshire utility analysis. Not official Eversource software. Annual PDF reports; no structured data API.",
        requires_api_key=False,
        access_type="manual_download",
        data_geography="nh",
        phase_added=1,
        is_real_data=True,
        is_mock_data=False,
        connector_implemented=False,
    ),

    # ── Test fixture only (not shown in production UI) ────────────────────────
    Source(
        id="mock_demand",
        name="Mock Electricity Demand",
        description="Synthetic hourly electricity demand data for New Hampshire. Used for automated tests and local development pipeline testing only.",
        category=SourceCategory.electricity,
        status=SourceStatus.test_fixture_only,
        update_frequency="On demand",
        data_format="CSV",
        notes="Generates realistic diurnal and weekly demand curves. Not real data. For tests and dev use only.",
        requires_api_key=False,
        auth_type="none",
        access_type="test_fixture_only",
        data_geography="nh",
        phase_added=2,
        last_verified="2026-04-27",
        is_real_data=False,
        is_mock_data=True,
        connector_implemented=True,
    ),
]

SOURCES_BY_ID: dict[str, Source] = {s.id: s for s in SOURCES}
